import type { Source } from "./types.ts";

/**
 * Every reference the site uses. Pages cite these with <Cite id="..." />.
 * Tests fail if a page cites an id that isn't here, if a source here is never
 * used, or if SOURCES.md is out of date (regenerate with `npm run sources`).
 *
 * `checked` records when the link and claim were confirmed against the live
 * page. Sources without it are listed in CONTENT_REVIEW.md as unverified.
 */
export const sources: Source[] = [
  {
    id: "investor-gov-glossary",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Investor.gov Glossary",
    publisher: "Investor.gov",
    year: "updated regularly",
    url: "https://www.investor.gov/introduction-investing/investing-basics/glossary",
    kind: "regulator",
    sections: ["general", "investing"],
    note: "Plain-language definitions of investing terms from the SEC.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-apr-vs-interest",
    authors: "Consumer Financial Protection Bureau",
    title: "What is the difference between a loan interest rate and the APR?",
    publisher: "Ask CFPB",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-loan-interest-rate-and-the-apr-en-733/",
    kind: "regulator",
    sections: ["general", "credit"],
    note: "APR includes the interest rate plus certain fees, expressed as a yearly rate.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-reg-dd",
    authors: "Consumer Financial Protection Bureau",
    title: "Regulation DD (Truth in Savings), 12 CFR Part 1030",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/rules-policy/regulations/1030/",
    kind: "regulator",
    sections: ["general"],
    note: "The federal rule that requires banks to disclose savings rates as an annual percentage yield (APY).",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-credit-score",
    authors: "Consumer Financial Protection Bureau",
    title: "What is a credit score?",
    publisher: "Ask CFPB",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-credit-score-en-315/",
    kind: "regulator",
    sections: ["general", "credit"],
    checked: "2026-10-05",
  },
  {
    id: "cfpb-credit-report",
    authors: "Consumer Financial Protection Bureau",
    title: "What is a credit report?",
    publisher: "Ask CFPB",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-credit-report-en-309/",
    kind: "regulator",
    sections: ["general", "credit"],
    checked: "2026-10-05",
  },
  {
    id: "cfpb-emergency-fund",
    authors: "Consumer Financial Protection Bureau",
    title: "An essential guide to building an emergency fund",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/an-essential-guide-to-building-an-emergency-fund/",
    kind: "regulator",
    sections: ["general", "investing", "budgeting"],
    checked: "2026-10-05",
  },
  {
    id: "cfpb-your-money-your-goals",
    authors: "Consumer Financial Protection Bureau",
    title: "Your Money, Your Goals: A financial empowerment toolkit",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/consumer-tools/educator-tools/your-money-your-goals/",
    kind: "regulator",
    sections: ["general"],
    note: "CFPB's toolkit for budgeting, saving and managing debt.",
    checked: "2026-10-05",
  },
  {
    id: "irs-tax-withholding",
    authors: "Internal Revenue Service",
    title: "Tax withholding",
    year: "updated regularly",
    url: "https://www.irs.gov/payments/tax-withholding",
    kind: "government",
    sections: ["general"],
    checked: "2026-10-05",
  },
  {
    id: "irs-401k-plans",
    authors: "Internal Revenue Service",
    title: "401(k) plans",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/401k-plans",
    kind: "government",
    sections: ["general", "investing"],
    checked: "2026-10-05",
  },
  {
    id: "irs-iras",
    authors: "Internal Revenue Service",
    title: "Individual retirement arrangements (IRAs)",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/individual-retirement-arrangements-iras",
    kind: "government",
    sections: ["general", "investing"],
    checked: "2026-10-05",
  },
  {
    id: "irs-roth-iras",
    authors: "Internal Revenue Service",
    title: "Roth IRAs",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/roth-iras",
    kind: "government",
    sections: ["general", "investing"],
    checked: "2026-10-05",
  },
  {
    id: "bls-cpi",
    authors: "U.S. Bureau of Labor Statistics",
    title: "Consumer Price Index (CPI)",
    year: "updated regularly",
    url: "https://www.bls.gov/cpi/",
    kind: "government",
    sections: ["general", "investing"],
    note: "The official U.S. measure of inflation for consumer prices.",
    checked: "2026-10-05",
  },
  {
    id: "investor-gov-advisers",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Investment Advisers",
    publisher: "Investor.gov",
    year: "updated regularly",
    url: "https://www.investor.gov/introduction-investing/getting-started/working-investment-professional/investment-advisers",
    kind: "regulator",
    sections: ["general"],
    note: "Investment advisers are fiduciaries required to act in your best interest; explains how they are paid and how to check their background.",
    checked: "2026-10-05",
  },
  {
    id: "hud-housing-counselors",
    authors: "U.S. Department of Housing and Urban Development",
    title: "About Housing Counseling",
    year: "updated regularly",
    url: "https://www.hud.gov/hud-partners/single-family-about-housing-counseling",
    kind: "government",
    sections: ["general", "credit"],
    note: "Foreclosure, eviction and homeless counseling are always free; other services may have a small fee.",
    checked: "2026-10-05",
  },
  {
    id: "nfcc",
    authors: "National Foundation for Credit Counseling",
    title: "NFCC: nonprofit credit counseling",
    year: "updated regularly",
    url: "https://www.nfcc.org/",
    kind: "practitioner",
    sections: ["general", "credit"],
    note: "The largest U.S. network of nonprofit credit counseling agencies.",
    checked: "2026-10-05",
  },
  {
    id: "irs-choosing-tax-pro",
    authors: "Internal Revenue Service",
    title: "Choosing a tax professional",
    year: "updated regularly",
    url: "https://www.irs.gov/tax-professionals/choosing-a-tax-professional",
    kind: "government",
    sections: ["general"],
    checked: "2026-10-05",
  },

  // ---------------- Investing ----------------
  {
    id: "markowitz-1952",
    authors: "Markowitz, H.",
    title: "Portfolio Selection",
    publisher: "The Journal of Finance, 7(1), 77–91",
    year: 1952,
    url: "https://doi.org/10.2307/2975974",
    kind: "academic",
    sections: ["investing"],
    note: "The founding paper of modern portfolio theory: combining assets reduces risk without necessarily reducing expected return.",
    checked: "2026-10-05",
  },
  {
    id: "statman-1987",
    authors: "Statman, M.",
    title: "How Many Stocks Make a Diversified Portfolio?",
    publisher: "Journal of Financial and Quantitative Analysis, 22(3), 353–363",
    year: 1987,
    url: "https://doi.org/10.2307/2330969",
    kind: "academic",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "bessembinder-2018",
    authors: "Bessembinder, H.",
    title: "Do Stocks Outperform Treasury Bills?",
    publisher: "Journal of Financial Economics, 129(3), 440–457",
    year: 2018,
    url: "https://doi.org/10.1016/j.jfineco.2018.06.004",
    kind: "academic",
    sections: ["investing"],
    note: "Most individual U.S. stocks since 1926 earned less over their lifetimes than one-month Treasury bills; a small minority produced all of the market's net gains.",
    checked: "2026-10-05",
  },
  {
    id: "sharpe-1991",
    authors: "Sharpe, W. F.",
    title: "The Arithmetic of Active Management",
    publisher: "Financial Analysts Journal, 47(1), 7–9",
    year: 1991,
    url: "https://doi.org/10.2469/faj.v47.n1.7",
    kind: "academic",
    sections: ["investing"],
    note: "Before costs, the average actively managed dollar must equal the market's return; after costs, it must trail it.",
    checked: "2026-10-05",
  },
  {
    id: "fama-french-2010",
    authors: "Fama, E. F. & French, K. R.",
    title: "Luck versus Skill in the Cross-Section of Mutual Fund Returns",
    publisher: "The Journal of Finance, 65(5), 1915–1947",
    year: 2010,
    url: "https://doi.org/10.1111/j.1540-6261.2010.01598.x",
    kind: "academic",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "fama-french-1993",
    authors: "Fama, E. F. & French, K. R.",
    title: "Common risk factors in the returns on stocks and bonds",
    publisher: "Journal of Financial Economics, 33(1), 3–56",
    year: 1993,
    url: "https://doi.org/10.1016/0304-405X(93)90023-5",
    kind: "academic",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "carhart-1997",
    authors: "Carhart, M. M.",
    title: "On Persistence in Mutual Fund Performance",
    publisher: "The Journal of Finance, 52(1), 57–82",
    year: 1997,
    url: "https://doi.org/10.1111/j.1540-6261.1997.tb03808.x",
    kind: "academic",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "spiva-us",
    authors: "S&P Dow Jones Indices",
    title: "SPIVA U.S. Scorecard",
    year: "updated regularly",
    url: "https://www.spglobal.com/spdji/en/research-insights/spiva/",
    kind: "industry",
    sections: ["investing"],
    note: "Twice-yearly comparison of actively managed funds against their benchmark indexes.",
    checked: "2026-10-05",
  },
  {
    id: "kinnel-2016",
    authors: "Kinnel, R.",
    title: "Fund Fees Predict Future Success or Failure",
    publisher: "Morningstar",
    year: 2016,
    url: "https://www.morningstar.com/funds/fund-fees-predict-future-success-or-failure",
    kind: "industry",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "bogle-2017",
    authors: "Bogle, J. C.",
    title: "The Little Book of Common Sense Investing (10th anniversary ed.)",
    publisher: "Wiley",
    year: 2017,
    url: "https://www.wiley.com/en-us/The+Little+Book+of+Common+Sense+Investing%3A+The+Only+Way+to+Guarantee+Your+Fair+Share+of+Stock+Market+Returns%2C+10th+Anniversary+Edition-p-9781119404507",
    kind: "practitioner",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "sec-fees-bulletin",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Investor Bulletin: How Fees and Expenses Affect Your Investment Portfolio",
    year: 2014,
    url: "https://www.sec.gov/investor/alerts/ib_fees_expenses.pdf",
    kind: "regulator",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "damodaran-returns",
    authors: "Damodaran, A.",
    title: "Historical Returns on Stocks, Bonds, Bills and Real Estate (annual dataset, 1928 to present)",
    publisher: "NYU Stern School of Business",
    year: "updated regularly",
    url: "https://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/histretSP.html",
    kind: "academic",
    sections: ["investing"],
    note: "Free yearly U.S. return data for stocks (S&P 500), 3-month Treasury bills, 10-year Treasury bonds, corporate bonds, real estate and inflation.",
    checked: "2026-10-05",
  },
  {
    id: "barber-odean-2000",
    authors: "Barber, B. M. & Odean, T.",
    title: "Trading Is Hazardous to Your Wealth: The Common Stock Investment Performance of Individual Investors",
    publisher: "The Journal of Finance, 55(2), 773–806",
    year: 2000,
    url: "https://doi.org/10.1111/0022-1082.00226",
    kind: "academic",
    sections: ["investing"],
    note: "Among 66,465 brokerage households (1991–1996), the most active traders earned 11.4% a year versus 17.9% for the market.",
    checked: "2026-10-05",
  },
  {
    id: "barber-et-al-2014",
    authors: "Barber, B. M., Lee, Y.-T., Liu, Y.-J. & Odean, T.",
    title: "The cross-section of speculator skill: Evidence from day trading",
    publisher: "Journal of Financial Markets, 18, 1–24",
    year: 2014,
    url: "https://doi.org/10.1016/j.finmar.2013.05.006",
    kind: "academic",
    sections: ["investing"],
    note: "In Taiwan's market, fewer than 1% of day traders were able to predictably profit net of fees.",
    checked: "2026-10-05",
  },
  {
    id: "kahneman-tversky-1979",
    authors: "Kahneman, D. & Tversky, A.",
    title: "Prospect Theory: An Analysis of Decision under Risk",
    publisher: "Econometrica, 47(2), 263–291",
    year: 1979,
    url: "https://doi.org/10.2307/1914185",
    kind: "academic",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "tversky-kahneman-1992",
    authors: "Tversky, A. & Kahneman, D.",
    title: "Advances in Prospect Theory: Cumulative Representation of Uncertainty",
    publisher: "Journal of Risk and Uncertainty, 5(4), 297–323",
    year: 1992,
    url: "https://doi.org/10.1007/BF00122574",
    kind: "academic",
    sections: ["investing"],
    note: "Estimated that losses weigh about 2.25 times as heavily as equal-sized gains.",
    checked: "2026-10-05",
  },
  {
    id: "tversky-kahneman-1974",
    authors: "Tversky, A. & Kahneman, D.",
    title: "Judgment under Uncertainty: Heuristics and Biases",
    publisher: "Science, 185(4157), 1124–1131",
    year: 1974,
    url: "https://doi.org/10.1126/science.185.4157.1124",
    kind: "academic",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "morningstar-mind-the-gap-2024",
    authors: "Morningstar (Ptak, J., with Arnott, A.)",
    title: "Mind the Gap 2024: A Report on Investor Returns in the US",
    publisher: "Morningstar",
    year: 2024,
    url: "https://www.morningstar.com/content/cs-assets/v3/assets/blt9415ea4cc4157833/bltebc45c862e642793/6759e563cbd7d6cef415ac94/Mind_the_Gap_2024.pdf",
    kind: "industry",
    sections: ["investing"],
    note: "Estimated that dollar-weighted investor returns trailed the funds' own total returns by about 1.1 percentage points a year over the 10 years ending 2023.",
    checked: "2026-10-05",
  },
  {
    id: "vanguard-cost-averaging-2023",
    authors: "Finlay, R. & Zorn, W.",
    title: "Cost averaging: Invest now or temporarily hold your cash?",
    publisher: "Vanguard Research",
    year: 2023,
    url: "https://corporate.vanguard.com/content/dam/corp/research/pdf/cost_averaging_invest_now_or_temporarily_hold_your_cash.pdf",
    kind: "industry",
    sections: ["investing"],
    note: "Investing a lump sum right away beat spreading it out over 12 months about 68% of the time. Vanguard's 2012 paper on the same question found about two-thirds.",
    checked: "2026-10-05",
  },
  {
    id: "vanguard-rebalancing",
    authors: "Jaconetti, C. M., Kinniry, F. M. & Zilbering, Y.",
    title: "Best practices for portfolio rebalancing",
    publisher: "Vanguard Research",
    year: 2010,
    url: "https://indexacapital.com/bundles/unaiadvisor/docs/papers/2010-Vanguard-Best-practices-for-portfolio-rebalancing.pdf",
    kind: "industry",
    sections: ["investing"],
    note: "Recommends checking once or twice a year and rebalancing when an asset class drifts about 5 percentage points. Vanguard no longer hosts the paper, so the link is a copy kept by another firm.",
    checked: "2026-10-05",
  },
  {
    id: "bogleheads-three-fund",
    authors: "Bogleheads",
    title: "Three-fund portfolio",
    publisher: "Bogleheads Wiki",
    year: "updated regularly",
    url: "https://www.bogleheads.org/wiki/Three-fund_portfolio",
    kind: "practitioner",
    sections: ["investing"],
  },
  {
    id: "bogleheads-prioritizing",
    authors: "Bogleheads",
    title: "Prioritizing investments",
    publisher: "Bogleheads Wiki",
    year: "updated regularly",
    url: "https://www.bogleheads.org/wiki/Prioritizing_investments",
    kind: "practitioner",
    sections: ["investing"],
    note: "The widely cited ordering: emergency fund, employer match, high-interest debt, then tax-advantaged accounts, then taxable.",
    checked: "2026-10-05",
  },
  {
    id: "investor-gov-asset-allocation",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Beginners' Guide to Asset Allocation, Diversification, and Rebalancing",
    publisher: "Investor.gov",
    year: "updated regularly",
    url: "https://www.investor.gov/additional-resources/general-resources/publications-research/info-sheets/beginners-guide-asset",
    kind: "regulator",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "investor-gov-target-date",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Target Date Funds – Investor Bulletin",
    publisher: "Investor.gov",
    year: 2025,
    url: "https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/target-date-funds-investor-bulletin",
    kind: "regulator",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "bengen-1994",
    authors: "Bengen, W. P.",
    title: "Determining Withdrawal Rates Using Historical Data",
    publisher: "Journal of Financial Planning, 7(4), 171–180",
    year: 1994,
    kind: "practitioner",
    url: "https://www.financialplanningassociation.org/sites/default/files/2021-04/MAR04%20Determining%20Withdrawal%20Rates%20Using%20Historical%20Data.pdf",
    sections: ["investing"],
    note: "Found that starting withdrawals at about 4% of savings, then raising them with inflation, survived every 30-year period in U.S. history he tested.",
    checked: "2026-10-05",
  },
  {
    id: "cooley-hubbard-walz-1998",
    authors: "Cooley, P. L., Hubbard, C. M. & Walz, D. T.",
    title: "Retirement Savings: Choosing a Withdrawal Rate That Is Sustainable",
    publisher: "AAII Journal, 20(2), 16–21",
    year: 1998,
    url: "https://www.aaii.com/journal/article/retirement-savings-choosing-a-withdrawal-rate-that-is-sustainable",
    kind: "academic",
    sections: ["investing"],
    note: 'The "Trinity study."',
    checked: "2026-10-05",
  },
  {
    id: "finke-pfau-blanchett-2013",
    authors: "Finke, M., Pfau, W. D. & Blanchett, D. M.",
    title: "The 4 Percent Rule Is Not Safe in a Low-Yield World",
    publisher: "Journal of Financial Planning, 26(6), 46–55",
    year: 2013,
    url: "https://www.financialplanningassociation.org/article/4-percent-rule-not-safe-low-yield-world",
    kind: "academic",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "guyton-klinger-2006",
    authors: "Guyton, J. T. & Klinger, W. J.",
    title: "Decision Rules and Maximum Initial Withdrawal Rates",
    publisher: "Journal of Financial Planning, 19(3), 48–58",
    year: 2006,
    url: "https://www.financialplanningassociation.org/article/journal/MAR06-decision-rules-and-maximum-initial-withdrawal-rates",
    kind: "practitioner",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "morningstar-retirement-income",
    authors: "Morningstar (Benz, C., Ptak, J. & Rekenthaler, J.)",
    title: "The State of Retirement Income",
    publisher: "Morningstar",
    year: "updated regularly",
    url: "https://www.morningstar.com/lp/the-state-of-retirement-income",
    kind: "industry",
    sections: ["investing"],
    note: 'Annual estimate of a "safe" starting withdrawal rate given current bond yields and valuations.',
    checked: "2026-10-05",
  },
  {
    id: "ssa-retirement",
    authors: "Social Security Administration",
    title: "Retirement benefits: how your benefit is calculated",
    year: "updated regularly",
    url: "https://www.ssa.gov/oact/progdata/retirebenefit1.html",
    kind: "government",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "ssa-my-account",
    authors: "Social Security Administration",
    title: "my Social Security account",
    year: "updated regularly",
    url: "https://www.ssa.gov/myaccount/",
    kind: "government",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "ssa-full-retirement-age",
    authors: "Social Security Administration",
    title: "Retirement age and benefit reduction",
    year: "updated regularly",
    url: "https://www.ssa.gov/benefits/retirement/planner/agereduction.html",
    kind: "government",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "ssa-fairness-act",
    authors: "Social Security Administration",
    title: "Social Security Fairness Act: Windfall Elimination Provision (WEP) and Government Pension Offset (GPO)",
    year: 2025,
    url: "https://www.ssa.gov/benefits/retirement/social-security-fairness-act.html",
    kind: "government",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "fed-inflation-target",
    authors: "Board of Governors of the Federal Reserve System",
    title: "Why does the Federal Reserve aim for inflation of 2 percent over the longer run?",
    year: "updated regularly",
    url: "https://www.federalreserve.gov/faqs/economy_14400.htm",
    kind: "government",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "fed-g19",
    authors: "Board of Governors of the Federal Reserve System",
    title: "Consumer Credit – G.19 (interest rates on credit card plans)",
    year: "updated regularly",
    url: "https://www.federalreserve.gov/releases/g19/current/default.htm",
    kind: "government",
    sections: ["investing", "credit"],
    checked: "2026-10-05",
  },
  {
    id: "irs-pub-969",
    authors: "Internal Revenue Service",
    title: "Publication 969: Health Savings Accounts and Other Tax-Favored Health Plans",
    year: "updated regularly",
    url: "https://www.irs.gov/publications/p969",
    kind: "government",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "irs-pub-590a",
    authors: "Internal Revenue Service",
    title: "Publication 590-A: Contributions to Individual Retirement Arrangements (IRAs)",
    year: "updated regularly",
    url: "https://www.irs.gov/publications/p590a",
    kind: "government",
    sections: ["investing"],
    note: "Includes the rule (from the SECURE Act of 2019) that taxable non-tuition fellowship and stipend payments count as compensation for IRA contributions.",
    checked: "2026-10-05",
  },
  {
    id: "irs-457b",
    authors: "Internal Revenue Service",
    title: "IRC 457(b) deferred compensation plans",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/irc-457b-deferred-compensation-plans",
    kind: "government",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "irs-403b",
    authors: "Internal Revenue Service",
    title: "IRC 403(b) tax-sheltered annuity plans",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/irc-403b-tax-sheltered-annuity-plans",
    kind: "government",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "investor-gov-red-flags",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Red Flags of Investment Fraud Checklist",
    publisher: "Investor.gov",
    year: "updated regularly",
    url: "https://www.investor.gov/protect-your-investments/fraud/how-avoid-fraud/red-flags-investment-fraud-checklist",
    kind: "regulator",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "investor-gov-ponzi",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Ponzi scheme",
    publisher: "Investor.gov",
    year: "updated regularly",
    url: "https://www.investor.gov/protect-your-investments/fraud/types-fraud/ponzi-scheme",
    kind: "regulator",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "investor-gov-crypto",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Exercise Caution with Crypto Asset Securities: Investor Alert",
    publisher: "Investor.gov",
    year: 2023,
    url: "https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-alerts/crypto-asset-securities",
    kind: "regulator",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "finra-day-trading",
    authors: "Financial Industry Regulatory Authority",
    title: "Frequent Intraday Trading: Understanding the Basics",
    publisher: "FINRA Investor Insights",
    year: 2026,
    url: "https://www.finra.org/investors/investing/investment-products/stocks/day-trading",
    kind: "regulator",
    sections: ["investing"],
    note: "Frequent intraday trading, especially on margin, risks losing some or all of your investment. Margin accounts need at least $2,000 of equity.",
    checked: "2026-10-05",
  },
  {
    id: "finra-brokercheck",
    authors: "Financial Industry Regulatory Authority",
    title: "BrokerCheck",
    year: "updated regularly",
    url: "https://brokercheck.finra.org/",
    kind: "regulator",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "fdic-deposit-insurance",
    authors: "Federal Deposit Insurance Corporation",
    title: "Deposit insurance",
    year: "updated regularly",
    url: "https://www.fdic.gov/resources/deposit-insurance",
    kind: "government",
    sections: ["investing"],
    note: "Bank deposits are insured up to $250,000 per depositor, per insured bank, for each account ownership category.",
    checked: "2026-10-05",
  },
  {
    id: "sec-interest-rate-risk",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Investor Bulletin: Interest Rate Risk — When Interest Rates Go Up, Prices of Fixed-Rate Bonds Fall",
    year: 2013,
    url: "https://www.sec.gov/files/ib_interestraterisk.pdf",
    kind: "regulator",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "treasurydirect-tips",
    authors: "U.S. Department of the Treasury",
    title: "Treasury Inflation-Protected Securities (TIPS) and I bonds",
    publisher: "TreasuryDirect",
    year: "updated regularly",
    url: "https://www.treasurydirect.gov/research-center/history-of-savings-bond/comparing-tips-to-i/",
    kind: "government",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "irs-topic-558",
    authors: "Internal Revenue Service",
    title: "Topic no. 558, Additional tax on early distributions from retirement plans other than IRAs",
    year: "updated regularly",
    url: "https://www.irs.gov/taxtopics/tc558",
    kind: "government",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "irs-topic-409",
    authors: "Internal Revenue Service",
    title: "Topic no. 409, Capital gains and losses",
    year: "updated regularly",
    url: "https://www.irs.gov/taxtopics/tc409",
    kind: "government",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "irs-pub-590b",
    authors: "Internal Revenue Service",
    title: "Publication 590-B: Distributions from Individual Retirement Arrangements (IRAs)",
    year: "updated regularly",
    url: "https://www.irs.gov/publications/p590b",
    kind: "government",
    sections: ["investing"],
    note: "Includes the ordering rules under which Roth IRA contributions come out before earnings.",
    checked: "2026-10-05",
  },
  {
    id: "dalbar-qaib",
    authors: "DALBAR, Inc.",
    title: "Quantitative Analysis of Investor Behavior (QAIB)",
    year: "updated regularly",
    url: "https://www.dalbar.com/",
    kind: "industry",
    sections: ["investing"],
    note: "Annual study of the gap between investor and fund returns; uses a different method from Morningstar's and typically reports larger gaps.",
    checked: "2026-10-05",
  },
  {
    id: "spdji-sp500",
    authors: "S&P Dow Jones Indices",
    title: "Daily Update: August 20, 2020",
    year: 2020,
    url: "https://www.spglobal.com/en/research-insights/market-insights/daily-update-august-20-2020",
    kind: "industry",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "ssa-trustees",
    authors: "Social Security Administration, Board of Trustees",
    title:
      "The Annual Report of the Board of Trustees of the Federal Old-Age and Survivors Insurance and Federal Disability Insurance Trust Funds",
    year: "updated regularly",
    url: "https://www.ssa.gov/oact/TR/",
    kind: "government",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "sec-variable-annuities",
    authors: "U.S. Securities and Exchange Commission",
    title: "Investor Tips: Variable Annuities",
    year: "updated regularly",
    url: "https://www.sec.gov/investor/pubs/varannty.htm",
    kind: "regulator",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "sec-iapd",
    authors: "U.S. Securities and Exchange Commission",
    title: "Investment Adviser Public Disclosure",
    year: "updated regularly",
    url: "https://adviserinfo.sec.gov/",
    kind: "regulator",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "sec-bitcoin-etp-2024",
    authors: "Gensler, G. (U.S. Securities and Exchange Commission)",
    title: "Statement on the Approval of Spot Bitcoin Exchange-Traded Products",
    year: 2024,
    url: "https://www.sec.gov/newsroom/speeches-statements/gensler-statement-spot-bitcoin-011023",
    kind: "regulator",
    sections: ["investing"],
    checked: "2026-10-05",
  },

  // ---------------- Budgeting ----------------
  {
    id: "warren-tyagi-2005",
    authors: "Warren, E. & Tyagi, A. W.",
    title: "All Your Worth: The Ultimate Lifetime Money Plan",
    publisher: "Free Press",
    year: 2005,
    url: "https://www.simonandschuster.com/books/All-Your-Worth/Elizabeth-Warren/A-Guide-to-Personal-Finances/9780743269889",
    kind: "practitioner",
    sections: ["budgeting"],
    note: "First published in hardcover in 2005; the link is the 2006 paperback edition.",
    checked: "2026-10-05",
  },
  {
    id: "pyhrr-1970",
    authors: "Pyhrr, P. A.",
    title: "Zero-base budgeting",
    publisher: "Harvard Business Review, 48(6), 111–121",
    year: 1970,
    kind: "practitioner",
    sections: ["budgeting"],
    note: "Introduced zero-based budgeting as a corporate planning method; personal-finance versions adapted it later. The article isn't freely online, so the link is a 1979 Nevada Legislative Counsel Bureau paper that cites it and describes Pyhrr's work at Texas Instruments.",
    checked: "2026-10-05",
    url: "https://www.leg.state.nv.us/Division/Research/Publications/Bkground/BP79-06.pdf",
  },
  {
    id: "clason-1926",
    authors: "Clason, G. S.",
    title: "The Richest Man in Babylon",
    year: 1926,
    url: "https://archive.org/details/clason-richest-man-in-babylon",
    kind: "practitioner",
    sections: ["budgeting"],
    note: 'Early popular source of the "pay yourself first" idea (saving a set share of income before spending).',
    checked: "2026-10-05",
  },
  {
    id: "thaler-benartzi-2004",
    authors: "Thaler, R. H. & Benartzi, S.",
    title: "Save More Tomorrow: Using Behavioral Economics to Increase Employee Saving",
    publisher: "Journal of Political Economy, 112(S1), S164–S187",
    year: 2004,
    url: "https://doi.org/10.1086/380085",
    kind: "academic",
    sections: ["budgeting"],
    note: "In the first implementation, participants' average saving rate rose from 3.5% to 13.6% over 40 months.",
    checked: "2026-10-05",
  },
  {
    id: "madrian-shea-2001",
    authors: "Madrian, B. C. & Shea, D. F.",
    title: "The Power of Suggestion: Inertia in 401(k) Participation and Savings Behavior",
    publisher: "The Quarterly Journal of Economics, 116(4), 1149–1187",
    year: 2001,
    url: "https://doi.org/10.1162/003355301753265543",
    kind: "academic",
    sections: ["budgeting"],
    note: "Automatic enrollment raised 401(k) participation among new employees from 37% to 86%.",
    checked: "2026-10-05",
  },
  {
    id: "johnson-goldstein-2003",
    authors: "Johnson, E. J. & Goldstein, D.",
    title: "Do Defaults Save Lives?",
    publisher: "Science, 302(5649), 1338–1339",
    year: 2003,
    url: "https://doi.org/10.1126/science.1091721",
    kind: "academic",
    sections: ["budgeting"],
    checked: "2026-10-05",
  },
  {
    id: "fed-shed",
    authors: "Board of Governors of the Federal Reserve System",
    title: "Economic Well-Being of U.S. Households (Survey of Household Economics and Decisionmaking)",
    year: "updated regularly",
    url: "https://www.federalreserve.gov/consumerscommunities/shed.htm",
    kind: "government",
    sections: ["budgeting"],
    note: "Annual survey including how adults would cover an unexpected $400 expense.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-bank-statements",
    authors: "Consumer Financial Protection Bureau",
    title: "Spending tracker (Your Money, Your Goals tool)",
    year: "updated regularly",
    url: "https://files.consumerfinance.gov/f/documents/cfpb_ymyg_disabilities_spending-tracker.pdf",
    kind: "regulator",
    sections: ["budgeting"],
    checked: "2026-10-05",
  },
  // ---------------- Credit and debt ----------------
  {
    id: "myfico-score-factors",
    authors: "FICO",
    title: "What's in my FICO Scores?",
    publisher: "myFICO",
    year: "updated regularly",
    url: "https://www.myfico.com/credit-education/whats-in-your-credit-score",
    kind: "industry",
    sections: ["general", "credit"],
    note: "Factor weights for the general population: payment history 35%, amounts owed 30%, length of history 15%, new credit 10%, credit mix 10%.",
    checked: "2026-10-05",
  },
  {
    id: "ftc-free-credit-reports",
    authors: "Federal Trade Commission",
    title: "Free Credit Reports",
    year: "updated regularly",
    url: "https://consumer.ftc.gov/articles/free-credit-reports",
    kind: "regulator",
    sections: ["credit"],
    note: "AnnualCreditReport.com is the official site for free reports from Equifax, Experian and TransUnion.",
    checked: "2026-10-05",
  },
  {
    id: "ftc-disputing-errors",
    authors: "Federal Trade Commission",
    title: "Disputing Errors on Your Credit Reports",
    year: "updated regularly",
    url: "https://consumer.ftc.gov/articles/disputing-errors-your-credit-reports",
    kind: "regulator",
    sections: ["credit"],
    checked: "2026-10-05",
  },
  {
    id: "cfpb-negative-info",
    authors: "Consumer Financial Protection Bureau",
    title: "How long does negative information remain on my credit report?",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/how-long-does-negative-information-remain-on-my-credit-report-en-323/",
    kind: "regulator",
    sections: ["credit"],
    note: "Most negative items stay about seven years; some bankruptcies up to ten.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-credit-reports-scores",
    authors: "Consumer Financial Protection Bureau",
    title: "Credit reports and scores",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/",
    kind: "regulator",
    sections: ["general", "credit"],
    note: "Guides on building credit, secured cards, and checking your own score.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-grace-period",
    authors: "Consumer Financial Protection Bureau",
    title: "What is a grace period for a credit card?",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-grace-period-for-a-credit-card-en-47/",
    kind: "regulator",
    sections: ["general", "credit"],
    checked: "2026-10-05",
  },
  {
    id: "cfpb-payday",
    authors: "Consumer Financial Protection Bureau",
    title: "What is a payday loan?",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-payday-loan-en-1567/",
    kind: "regulator",
    sections: ["credit"],
    note: "A typical two-week fee of $15 per $100 borrowed equals an APR of almost 400%.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-bnpl-2022",
    authors: "Consumer Financial Protection Bureau",
    title: "Buy Now, Pay Later: Market trends and consumer impacts",
    year: 2022,
    url: "https://www.consumerfinance.gov/data-research/research-reports/buy-now-pay-later-market-trends-and-consumer-impacts/",
    kind: "regulator",
    sections: ["credit"],
    checked: "2026-10-05",
  },
  {
    id: "cfpb-auto-loans",
    authors: "Consumer Financial Protection Bureau",
    title: "Auto loans",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/consumer-tools/auto-loans/",
    kind: "regulator",
    sections: ["credit"],
    checked: "2026-10-05",
  },
  {
    id: "studentaid-loans",
    authors: "U.S. Department of Education, Federal Student Aid",
    title: "Subsidized and Unsubsidized Loans",
    year: "updated regularly",
    url: "https://studentaid.gov/understand-aid/types/loans/subsidized-unsubsidized",
    kind: "government",
    sections: ["credit"],
    note: "Federal loan types, who qualifies, and current borrowing limits.",
  },
  {
    id: "studentaid-rates",
    authors: "U.S. Department of Education, Federal Student Aid",
    title: "Federal Interest Rates and Fees",
    year: "updated regularly",
    url: "https://studentaid.gov/understand-aid/types/loans/interest-rates",
    kind: "government",
    sections: ["credit"],
  },
  {
    id: "studentaid-pslf",
    authors: "U.S. Department of Education, Federal Student Aid",
    title: "Public Service Loan Forgiveness (PSLF)",
    year: "updated regularly",
    url: "https://studentaid.gov/manage-loans/forgiveness-cancellation/public-service",
    kind: "government",
    sections: ["general", "credit"],
    note: "Forgives the remaining balance on Direct Loans after 120 qualifying payments while working full time for a government or qualifying nonprofit employer.",
  },
  {
    id: "cfpb-dti",
    authors: "Consumer Financial Protection Bureau",
    title: "What is a debt-to-income ratio?",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-debt-to-income-ratio-en-1791/",
    kind: "regulator",
    sections: ["general", "credit"],
    checked: "2026-10-05",
  },
  {
    id: "cfpb-pmi",
    authors: "Consumer Financial Protection Bureau",
    title: "What is private mortgage insurance?",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-is-private-mortgage-insurance-en-122/",
    kind: "regulator",
    sections: ["general", "credit"],
    checked: "2026-10-05",
  },
  {
    id: "amar-et-al-2011",
    authors: "Amar, M., Ariely, D., Ayal, S., Cryder, C. E. & Rick, S. I.",
    title: "Winning the Battle but Losing the War: The Psychology of Debt Management",
    publisher: "Journal of Marketing Research, 48(SPL), S38–S50",
    year: 2011,
    url: "https://doi.org/10.1509/jmkr.48.SPL.S38",
    kind: "academic",
    sections: ["credit"],
    note: 'In experiments, people tended to pay off small debts first even when that cost more interest ("debt account aversion").',
    checked: "2026-10-05",
  },
  {
    id: "gal-mcshane-2012",
    authors: "Gal, D. & McShane, B. B.",
    title: "Can Small Victories Help Win the War? Evidence from Consumer Debt Management",
    publisher: "Journal of Marketing Research, 49(4), 487–501",
    year: 2012,
    url: "https://doi.org/10.1509/jmr.11.0272",
    kind: "academic",
    sections: ["credit"],
    note: "In data from a debt settlement program, closing off individual debts predicted eventually eliminating all debt.",
    checked: "2026-10-05",
  },
  {
    id: "kettle-et-al-2016",
    authors: "Kettle, K. L., Trudel, R., Blanchard, S. J. & Häubl, G.",
    title: "Repayment Concentration and Consumer Motivation to Get Out of Debt",
    publisher: "Journal of Consumer Research, 43(3), 460–477",
    year: 2016,
    url: "https://doi.org/10.1093/jcr/ucw037",
    kind: "academic",
    sections: ["credit"],
    note: "Concentrating payments on one account at a time was linked to more progress paying debt down.",
    checked: "2026-10-05",
  },
  {
    id: "uscourts-bankruptcy",
    authors: "Administrative Office of the U.S. Courts",
    title: "Chapter 7: Bankruptcy Basics",
    year: "updated regularly",
    url: "https://www.uscourts.gov/court-programs/bankruptcy/bankruptcy-basics/chapter-7-bankruptcy-basics",
    kind: "government",
    sections: ["credit"],
    checked: "2026-10-05",
  },
  {
    id: "doj-ust-counseling",
    authors: "U.S. Department of Justice, U.S. Trustee Program",
    title: "Credit Counseling & Debtor Education Courses",
    year: "updated regularly",
    url: "https://www.justice.gov/ust/credit-counseling-debtor-education-information",
    kind: "government",
    sections: ["credit"],
    note: "Most people must take an approved credit counseling course before filing for bankruptcy.",
    checked: "2026-10-05",
  },
  {
    id: "ftc-debt-relief",
    authors: "Federal Trade Commission",
    title: "How To Get Out of Debt",
    year: "updated regularly",
    url: "https://consumer.ftc.gov/articles/how-get-out-debt",
    kind: "regulator",
    sections: ["credit"],
    note: "Compares credit counseling, debt settlement and bankruptcy, and warns about debt relief scams.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-debt-collection",
    authors: "Consumer Financial Protection Bureau",
    title: "Debt collection",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/consumer-tools/debt-collection/",
    kind: "regulator",
    sections: ["credit"],
    checked: "2026-10-05",
  },
  {
    id: "jorda-et-al-2019",
    authors: "Jordà, Ò., Knoll, K., Kuvshinov, D., Schularick, M. & Taylor, A. M.",
    title: "The Rate of Return on Everything, 1870–2015",
    publisher: "The Quarterly Journal of Economics, 134(3), 1225–1298",
    year: 2019,
    url: "https://doi.org/10.1093/qje/qjz012",
    kind: "academic",
    sections: ["credit"],
    note: "Across 16 countries, housing's total return (price gains plus rent) was similar to stocks' over the long run, with less volatility.",
    checked: "2026-10-05",
  },
  {
    id: "ca-boe-property-tax",
    authors: "California State Board of Equalization",
    title: "California Property Tax: An Overview (Publication 29)",
    year: "updated regularly",
    url: "https://www.boe.ca.gov/proptaxes/pdf/pub29.pdf",
    kind: "government",
    sections: ["credit"],
    note: "Proposition 13 limits the base property tax rate to 1% of assessed value, plus voter-approved local additions.",
    checked: "2026-10-05",
  },
  {
    id: "fred-case-shiller",
    authors: "S&P Dow Jones Indices, via Federal Reserve Bank of St. Louis (FRED)",
    title: "S&P Cotality Case-Shiller U.S. National Home Price Index (CSUSHPINSA)",
    year: "updated regularly",
    url: "https://fred.stlouisfed.org/series/CSUSHPINSA",
    kind: "industry",
    sections: ["credit"],
    note: "National home prices peaked in 2006 and fell for several years before recovering.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-start-rebuild-credit",
    authors: "Consumer Financial Protection Bureau",
    title: "What are some ways to start or rebuild a good credit history?",
    publisher: "Ask CFPB",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-are-some-ways-to-start-or-rebuild-a-good-credit-history-en-2155/",
    kind: "regulator",
    sections: ["general", "credit"],
    note: "Describes secured credit cards, credit builder loans and store cards as ways to start building credit.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-credit-myths",
    authors: "Consumer Financial Protection Bureau",
    title: "Credit score myths that might be holding you back from improving your credit",
    publisher: "CFPB blog",
    year: 2019,
    url: "https://www.consumerfinance.gov/archive/blog/credit-score-myths-might-be-holding-you-back-improving-your-credit/",
    kind: "regulator",
    sections: ["credit"],
    note: "Paying cards in full is best for your score, checking your own reports doesn't affect it, and closing cards can raise utilization.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-how-much-to-spend",
    authors: "Consumer Financial Protection Bureau",
    title: "Figure out how much you want to spend",
    publisher: "Buying a House",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/owning-a-home/prepare/figure-out-how-much-you-want-to-spend/",
    kind: "regulator",
    sections: ["credit"],
    note: "Closing costs typically range from 2% to 5% of the purchase price.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-credit-card-apr",
    authors: "Consumer Financial Protection Bureau",
    title: "What is a credit card interest rate? What does APR mean?",
    publisher: "Ask CFPB",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-credit-card-interest-rate-what-does-apr-mean-en-44/",
    kind: "regulator",
    sections: ["credit"],
    note: "Credit card interest rates are stated as a yearly rate called the APR.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-amortization",
    authors: "Consumer Financial Protection Bureau",
    title: "What is amortization and how could it affect my auto loan?",
    publisher: "Ask CFPB",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-is-amortization-and-how-could-it-affect-my-auto-loan-en-771/",
    kind: "regulator",
    sections: ["general"],
    note: "With a fixed monthly payment, more of each early payment goes to interest and more of each later one to principal.",
    checked: "2026-10-05",
  },
  {
    id: "cfpb-auto-loan-total-cost",
    authors: "Consumer Financial Protection Bureau",
    title: "Don't get taken for a ride; protect yourself from an auto loan you can't afford",
    publisher: "CFPB blog",
    year: 2016,
    url: "https://www.consumerfinance.gov/archive/blog/dont-get-taken-ride-protect-yourself-auto-loan-you-cant-afford/",
    kind: "regulator",
    sections: ["credit"],
    note: "Compare the total cost of financing offers; a smaller monthly payment can mean a longer loan with more interest.",
    checked: "2026-10-05",
  },
  {
    id: "nasfaa-obbb-loans",
    authors: "National Association of Student Financial Aid Administrators",
    title: "Federal Student Aid Changes in the One Big Beautiful Bill Act",
    publisher: "NASFAA",
    year: 2025,
    url: "https://www.nasfaa.org/uploads/documents/Federal_Student_Aid_Change_OB3.pdf",
    kind: "industry",
    sections: ["credit"],
    note: "From July 1, 2026: Grad PLUS ends for new borrowers; graduate students can borrow up to $20,500 a year and $100,000 in total in Direct Unsubsidized Loans.",
    checked: "2026-10-05",
  },
  {
    id: "fsa-rates-2026-27",
    authors: "U.S. Department of Education, Federal Student Aid",
    title: "Interest Rates for Federal Direct Loans First Disbursed Between July 1, 2026, and June 30, 2027",
    publisher: "FSA Partner Connect",
    year: 2026,
    url: "https://fsapartners.ed.gov/knowledge-center/library/electronic-announcements/2026-06-04/interest-rates-federal-direct-loans-first-disbursed-between-july-1-2026-and-june-30-2027",
    kind: "government",
    sections: ["credit"],
    note: "Fixed rate of 8.07% on Direct Unsubsidized Loans for graduate students for 2026-27.",
    checked: "2026-10-05",
  },
  {
    id: "uscourts-chapter-13",
    authors: "Administrative Office of the U.S. Courts",
    title: "Chapter 13: Bankruptcy Basics",
    year: "updated regularly",
    url: "https://www.uscourts.gov/court-programs/bankruptcy/bankruptcy-basics/chapter-13-bankruptcy-basics",
    kind: "government",
    sections: ["credit"],
    checked: "2026-10-05",
  },
  {
    id: "sp-case-shiller-2012",
    authors: "S&P Dow Jones Indices",
    title: "All Three Home Price Composites End 2011 at New Lows According to the S&P/Case-Shiller Home Price Indices",
    publisher: "S&P press release",
    year: 2012,
    url: "https://press.spglobal.com/2012-02-28-All-Three-Home-Price-Composites-End-2011-at-New-Lows-According-to-the-S-P-Case-Shiller-Home-Price-Indices",
    kind: "industry",
    sections: ["credit"],
    note: "The national index ended 2011 down 33.8% from its 2006 peak.",
    checked: "2026-10-05",
  },
  {
    id: "irs-deferral-multiple-plans",
    authors: "Internal Revenue Service",
    title: "How much salary can you defer if you're eligible for more than one retirement plan?",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/how-much-salary-can-you-defer-if-youre-eligible-for-more-than-one-retirement-plan",
    kind: "government",
    sections: ["investing"],
    note: "Deferrals to a 457(b) plan aren't combined with deferrals to a 403(b) or other plans, so each has its own limit.",
    checked: "2026-10-05",
  },
  {
    id: "investor-gov-pump-dump",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Pump and Dump Schemes",
    publisher: "Investor.gov",
    year: "updated regularly",
    url: "https://www.investor.gov/protect-your-investments/fraud/types-fraud/pump-and-dump-schemes",
    kind: "regulator",
    sections: ["investing"],
    checked: "2026-10-05",
  },
  {
    id: "irs-vesting",
    authors: "Internal Revenue Service",
    title: "Retirement topics: Vesting",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/plan-participant-employee/retirement-topics-vesting",
    kind: "government",
    sections: ["investing"],
    note: "Your own contributions are always 100% yours; employer contributions to a 401(k) can vest over up to six years of service.",
    checked: "2026-10-05",
  },
  {
    id: "irs-ira-limits",
    authors: "Internal Revenue Service",
    title: "Retirement topics: IRA contribution limits",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/plan-participant-employee/retirement-topics-ira-contribution-limits",
    kind: "government",
    sections: ["general"],
    note: "You can contribute up to the annual limit or your taxable compensation for the year, whichever is less.",
    checked: "2026-10-05",
  },
];

export const sourcesById: ReadonlyMap<string, Source> = new Map(sources.map((s) => [s.id, s]));

export function getSource(id: string): Source {
  const s = sourcesById.get(id);
  if (!s) throw new Error(`Unknown source id "${id}". Add it to src/content/sources.ts.`);
  return s;
}

/** A short "Author, Year" label for inline citations. */
export function shortCitation(s: Source): string {
  const shortAuthor = institutionShortName(s.authors);
  return typeof s.year === "number" ? `${shortAuthor}, ${s.year}` : shortAuthor;
}

const institutionAbbreviations: Array<[RegExp, string]> = [
  [/Securities and Exchange Commission/, "SEC"],
  [/Consumer Financial Protection Bureau/, "CFPB"],
  [/Federal Trade Commission/, "FTC"],
  [/Internal Revenue Service/, "IRS"],
  [/Bureau of Labor Statistics/, "BLS"],
  [/Housing and Urban Development/, "HUD"],
  [/Financial Industry Regulatory Authority/, "FINRA"],
  [/Federal Reserve/, "Federal Reserve"],
  [/National Foundation for Credit Counseling/, "NFCC"],
];

function institutionShortName(authors: string): string {
  for (const [re, abbr] of institutionAbbreviations) {
    if (re.test(authors)) return abbr;
  }
  // People: "Sharpe, W. F." -> "Sharpe"; "Barber, B. M. & Odean, T." -> "Barber & Odean".
  const people = authors
    .split(/\s*(?:&|\band\b)\s*/)
    .flatMap((part) => part.split(/,\s*(?=[A-Z][a-z])/))
    .map((a) => a.split(",")[0].trim());
  if (people.length > 2) return `${people[0]} et al.`;
  return people.join(" & ");
}

/** Full reference in a consistent, readable format. */
export function fullCitation(s: Source): string {
  const year = typeof s.year === "number" ? ` (${s.year}).` : ".";
  const publisher = s.publisher ? ` ${s.publisher}.` : "";
  return `${s.authors}${year} ${s.title}${endPunct(s.title)}${publisher}`;
}

/** A period after a title, unless it already ends in punctuation. */
export function endPunct(title: string): string {
  return /[.?!]$/.test(title) ? "" : ".";
}
