import type { Source } from "./types.ts";

/**
 * Every reference the site uses. Pages cite these with <Cite id="..." />.
 * Tests fail if a page cites an id that isn't here, if a source here is never
 * used, or if SOURCES.md is out of date (regenerate with `npm run sources`).
 *
 * `checked` records when the link and claim were confirmed against the live
 * page. Sources without it are listed in CONTENT_REVIEW.md as unverified.
 */
export const sources: Source[] = [
  {
    id: "investor-gov-glossary",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Investor.gov Glossary",
    publisher: "Investor.gov",
    year: "updated regularly",
    url: "https://www.investor.gov/introduction-investing/investing-basics/glossary",
    kind: "regulator",
    sections: ["general", "investing"],
    note: "Plain-language definitions of investing terms from the SEC.",
  },
  {
    id: "cfpb-apr-vs-interest",
    authors: "Consumer Financial Protection Bureau",
    title: "What is the difference between a loan interest rate and the APR?",
    publisher: "Ask CFPB",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-loan-interest-rate-and-the-apr-en-733/",
    kind: "regulator",
    sections: ["general"],
    note: "APR includes the interest rate plus certain fees, expressed as a yearly rate.",
  },
  {
    id: "cfpb-reg-dd",
    authors: "Consumer Financial Protection Bureau",
    title: "Regulation DD (Truth in Savings), 12 CFR Part 1030",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/rules-policy/regulations/1030/",
    kind: "regulator",
    sections: ["general"],
    note: "The federal rule that requires banks to disclose savings rates as an annual percentage yield (APY).",
  },
  {
    id: "cfpb-credit-score",
    authors: "Consumer Financial Protection Bureau",
    title: "What is a credit score?",
    publisher: "Ask CFPB",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-credit-score-en-315/",
    kind: "regulator",
    sections: ["general"],
  },
  {
    id: "cfpb-credit-report",
    authors: "Consumer Financial Protection Bureau",
    title: "What is a credit report?",
    publisher: "Ask CFPB",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-credit-report-en-309/",
    kind: "regulator",
    sections: ["general"],
  },
  {
    id: "cfpb-emergency-fund",
    authors: "Consumer Financial Protection Bureau",
    title: "An essential guide to building an emergency fund",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/an-essential-guide-to-building-an-emergency-fund/",
    kind: "regulator",
    sections: ["general", "investing", "budgeting"],
  },
  {
    id: "cfpb-your-money-your-goals",
    authors: "Consumer Financial Protection Bureau",
    title: "Your Money, Your Goals: A financial empowerment toolkit",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/consumer-tools/educator-tools/your-money-your-goals/",
    kind: "regulator",
    sections: ["general"],
    note: "CFPB's toolkit for budgeting, saving and managing debt.",
  },
  {
    id: "irs-tax-withholding",
    authors: "Internal Revenue Service",
    title: "Tax withholding",
    year: "updated regularly",
    url: "https://www.irs.gov/payments/tax-withholding",
    kind: "government",
    sections: ["general"],
  },
  {
    id: "irs-401k-plans",
    authors: "Internal Revenue Service",
    title: "401(k) plans",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/401k-plans",
    kind: "government",
    sections: ["general", "investing"],
  },
  {
    id: "irs-iras",
    authors: "Internal Revenue Service",
    title: "Individual retirement arrangements (IRAs)",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/individual-retirement-arrangements-iras",
    kind: "government",
    sections: ["general", "investing"],
  },
  {
    id: "irs-roth-iras",
    authors: "Internal Revenue Service",
    title: "Roth IRAs",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/roth-iras",
    kind: "government",
    sections: ["general", "investing"],
  },
  {
    id: "bls-cpi",
    authors: "U.S. Bureau of Labor Statistics",
    title: "Consumer Price Index (CPI)",
    year: "updated regularly",
    url: "https://www.bls.gov/cpi/",
    kind: "government",
    sections: ["general", "investing"],
    note: "The official U.S. measure of inflation for consumer prices.",
  },
  {
    id: "cfpb-financial-advisor",
    authors: "Consumer Financial Protection Bureau",
    title: "Choosing a financial advisor",
    publisher: "Ask CFPB",
    year: "updated regularly",
    url: "https://www.consumerfinance.gov/consumer-tools/retirement/choosing-financial-advisor/",
    kind: "regulator",
    sections: ["general"],
    note: "How to check an advisor's background and whether they act as a fiduciary.",
  },
  {
    id: "hud-housing-counselors",
    authors: "U.S. Department of Housing and Urban Development",
    title: "Find a HUD-approved housing counseling agency",
    year: "updated regularly",
    url: "https://www.hud.gov/counseling",
    kind: "government",
    sections: ["general"],
  },
  {
    id: "nfcc",
    authors: "National Foundation for Credit Counseling",
    title: "NFCC: nonprofit credit counseling",
    year: "updated regularly",
    url: "https://www.nfcc.org/",
    kind: "practitioner",
    sections: ["general"],
    note: "The largest U.S. network of nonprofit credit counseling agencies.",
  },
  {
    id: "irs-choosing-tax-pro",
    authors: "Internal Revenue Service",
    title: "Choosing a tax professional",
    year: "updated regularly",
    url: "https://www.irs.gov/tax-professionals/choosing-a-tax-professional",
    kind: "government",
    sections: ["general"],
  },

  // ---------------- Investing ----------------
  {
    id: "markowitz-1952",
    authors: "Markowitz, H.",
    title: "Portfolio Selection",
    publisher: "The Journal of Finance, 7(1), 77–91",
    year: 1952,
    url: "https://doi.org/10.2307/2975974",
    kind: "academic",
    sections: ["investing"],
    note: "The founding paper of modern portfolio theory: combining assets reduces risk without necessarily reducing expected return.",
  },
  {
    id: "statman-1987",
    authors: "Statman, M.",
    title: "How Many Stocks Make a Diversified Portfolio?",
    publisher: "Journal of Financial and Quantitative Analysis, 22(3), 353–363",
    year: 1987,
    url: "https://doi.org/10.2307/2330969",
    kind: "academic",
    sections: ["investing"],
  },
  {
    id: "bessembinder-2018",
    authors: "Bessembinder, H.",
    title: "Do Stocks Outperform Treasury Bills?",
    publisher: "Journal of Financial Economics, 129(3), 440–457",
    year: 2018,
    url: "https://doi.org/10.1016/j.jfineco.2018.06.004",
    kind: "academic",
    sections: ["investing"],
    note: "Most individual U.S. stocks since 1926 earned less over their lifetimes than one-month Treasury bills; a small minority produced all of the market's net gains.",
  },
  {
    id: "sharpe-1991",
    authors: "Sharpe, W. F.",
    title: "The Arithmetic of Active Management",
    publisher: "Financial Analysts Journal, 47(1), 7–9",
    year: 1991,
    url: "https://doi.org/10.2469/faj.v47.n1.7",
    kind: "academic",
    sections: ["investing"],
    note: "Before costs, the average actively managed dollar must equal the market's return; after costs, it must trail it.",
  },
  {
    id: "fama-french-2010",
    authors: "Fama, E. F. & French, K. R.",
    title: "Luck versus Skill in the Cross-Section of Mutual Fund Returns",
    publisher: "The Journal of Finance, 65(5), 1915–1947",
    year: 2010,
    url: "https://doi.org/10.1111/j.1540-6261.2010.01598.x",
    kind: "academic",
    sections: ["investing"],
  },
  {
    id: "fama-french-1993",
    authors: "Fama, E. F. & French, K. R.",
    title: "Common risk factors in the returns on stocks and bonds",
    publisher: "Journal of Financial Economics, 33(1), 3–56",
    year: 1993,
    url: "https://doi.org/10.1016/0304-405X(93)90023-5",
    kind: "academic",
    sections: ["investing"],
  },
  {
    id: "carhart-1997",
    authors: "Carhart, M. M.",
    title: "On Persistence in Mutual Fund Performance",
    publisher: "The Journal of Finance, 52(1), 57–82",
    year: 1997,
    url: "https://doi.org/10.1111/j.1540-6261.1997.tb03808.x",
    kind: "academic",
    sections: ["investing"],
  },
  {
    id: "spiva-us",
    authors: "S&P Dow Jones Indices",
    title: "SPIVA U.S. Scorecard",
    year: "updated regularly",
    url: "https://www.spglobal.com/spdji/en/research-insights/spiva/",
    kind: "industry",
    sections: ["investing"],
    note: "Twice-yearly comparison of actively managed funds against their benchmark indexes.",
  },
  {
    id: "kinnel-2016",
    authors: "Kinnel, R.",
    title: "Fund Fees Predict Future Success or Failure",
    publisher: "Morningstar",
    year: 2016,
    url: "https://www.morningstar.com/funds/fund-fees-predict-future-success-or-failure",
    kind: "industry",
    sections: ["investing"],
  },
  {
    id: "bogle-2017",
    authors: "Bogle, J. C.",
    title: "The Little Book of Common Sense Investing (10th anniversary ed.)",
    publisher: "Wiley",
    year: 2017,
    url: "https://www.wiley.com/en-us/The+Little+Book+of+Common+Sense+Investing%3A+The+Only+Way+to+Guarantee+Your+Fair+Share+of+Stock+Market+Returns%2C+10th+Anniversary+Edition-p-9781119404507",
    kind: "practitioner",
    sections: ["investing"],
  },
  {
    id: "sec-fees-bulletin",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Investor Bulletin: How Fees and Expenses Affect Your Investment Portfolio",
    year: 2014,
    url: "https://www.sec.gov/investor/alerts/ib_fees_expenses.pdf",
    kind: "regulator",
    sections: ["investing"],
  },
  {
    id: "damodaran-returns",
    authors: "Damodaran, A.",
    title: "Historical Returns on Stocks, Bonds, Bills and Real Estate (annual dataset, 1928 to present)",
    publisher: "NYU Stern School of Business",
    year: "updated regularly",
    url: "https://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/histretSP.html",
    kind: "academic",
    sections: ["investing"],
    note: "Free yearly U.S. return data for stocks (S&P 500), 3-month Treasury bills, 10-year Treasury bonds, corporate bonds, real estate and inflation.",
  },
  {
    id: "barber-odean-2000",
    authors: "Barber, B. M. & Odean, T.",
    title: "Trading Is Hazardous to Your Wealth: The Common Stock Investment Performance of Individual Investors",
    publisher: "The Journal of Finance, 55(2), 773–806",
    year: 2000,
    url: "https://doi.org/10.1111/0022-1082.00226",
    kind: "academic",
    sections: ["investing"],
    note: "Among 66,465 brokerage households (1991–1996), the most active traders earned 11.4% a year versus 17.9% for the market.",
  },
  {
    id: "barber-et-al-2014",
    authors: "Barber, B. M., Lee, Y.-T., Liu, Y.-J. & Odean, T.",
    title: "The cross-section of speculator skill: Evidence from day trading",
    publisher: "Journal of Financial Markets, 18, 1–24",
    year: 2014,
    url: "https://doi.org/10.1016/j.finmar.2013.05.006",
    kind: "academic",
    sections: ["investing"],
    note: "In Taiwan's market, fewer than 1% of day traders were able to predictably profit net of fees.",
  },
  {
    id: "kahneman-tversky-1979",
    authors: "Kahneman, D. & Tversky, A.",
    title: "Prospect Theory: An Analysis of Decision under Risk",
    publisher: "Econometrica, 47(2), 263–291",
    year: 1979,
    url: "https://doi.org/10.2307/1914185",
    kind: "academic",
    sections: ["investing"],
  },
  {
    id: "tversky-kahneman-1992",
    authors: "Tversky, A. & Kahneman, D.",
    title: "Advances in Prospect Theory: Cumulative Representation of Uncertainty",
    publisher: "Journal of Risk and Uncertainty, 5(4), 297–323",
    year: 1992,
    url: "https://doi.org/10.1007/BF00122574",
    kind: "academic",
    sections: ["investing"],
    note: "Estimated that losses weigh about 2.25 times as heavily as equal-sized gains.",
  },
  {
    id: "tversky-kahneman-1974",
    authors: "Tversky, A. & Kahneman, D.",
    title: "Judgment under Uncertainty: Heuristics and Biases",
    publisher: "Science, 185(4157), 1124–1131",
    year: 1974,
    url: "https://doi.org/10.1126/science.185.4157.1124",
    kind: "academic",
    sections: ["investing"],
  },
  {
    id: "morningstar-mind-the-gap-2024",
    authors: "Morningstar (Arnott, A.)",
    title: "Mind the Gap 2024: A Report on Investor Returns in the US",
    publisher: "Morningstar",
    year: 2024,
    url: "https://www.morningstar.com/lp/mind-the-gap",
    kind: "industry",
    sections: ["investing"],
    note: "Estimated that dollar-weighted investor returns trailed the funds' own total returns by about 1.1 percentage points a year over the 10 years ending 2023.",
  },
  {
    id: "vanguard-dca-2012",
    authors: "Shtekhman, A., Tasopoulos, C. & Wimmer, B.",
    title: "Dollar-cost averaging just means taking risk later",
    publisher: "Vanguard Research",
    year: 2012,
    url: "https://corporate.vanguard.com/content/dam/corp/research/pdf/Dollar-cost-averaging-just-means-taking-risk-later.pdf",
    kind: "industry",
    sections: ["investing"],
    note: "Historically, investing a lump sum immediately beat spreading it out over 12 months about two-thirds of the time.",
  },
  {
    id: "vanguard-rebalancing",
    authors: "Jaconetti, C. M., Kinniry, F. M. & Zilbering, Y.",
    title: "Best practices for portfolio rebalancing",
    publisher: "Vanguard Research",
    year: 2010,
    url: "https://corporate.vanguard.com/content/dam/corp/research/pdf/Best-practices-for-portfolio-rebalancing.pdf",
    kind: "industry",
    sections: ["investing"],
  },
  {
    id: "bogleheads-three-fund",
    authors: "Bogleheads",
    title: "Three-fund portfolio",
    publisher: "Bogleheads Wiki",
    year: "updated regularly",
    url: "https://www.bogleheads.org/wiki/Three-fund_portfolio",
    kind: "practitioner",
    sections: ["investing"],
  },
  {
    id: "bogleheads-prioritizing",
    authors: "Bogleheads",
    title: "Prioritizing investments",
    publisher: "Bogleheads Wiki",
    year: "updated regularly",
    url: "https://www.bogleheads.org/wiki/Prioritizing_investments",
    kind: "practitioner",
    sections: ["investing"],
    note: "The widely cited ordering: emergency fund, employer match, high-interest debt, then tax-advantaged accounts, then taxable.",
  },
  {
    id: "investor-gov-asset-allocation",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Beginners' Guide to Asset Allocation, Diversification, and Rebalancing",
    publisher: "Investor.gov",
    year: "updated regularly",
    url: "https://www.investor.gov/additional-resources/general-resources/publications-research/info-sheets/beginners-guide-asset",
    kind: "regulator",
    sections: ["investing"],
  },
  {
    id: "investor-gov-target-date",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Investor Bulletin: Target Date Retirement Funds",
    publisher: "Investor.gov",
    year: "updated regularly",
    url: "https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/investor-14",
    kind: "regulator",
    sections: ["investing"],
  },
  {
    id: "bengen-1994",
    authors: "Bengen, W. P.",
    title: "Determining Withdrawal Rates Using Historical Data",
    publisher: "Journal of Financial Planning, 7(4), 171–180",
    year: 1994,
    kind: "practitioner",
    url: "https://www.financialplanningassociation.org/sites/default/files/2021-04/MAR04%20Determining%20Withdrawal%20Rates%20Using%20Historical%20Data.pdf",
    sections: ["investing"],
    note: "Found that starting withdrawals at about 4% of savings, then raising them with inflation, survived every 30-year period in U.S. history he tested.",
  },
  {
    id: "cooley-hubbard-walz-1998",
    authors: "Cooley, P. L., Hubbard, C. M. & Walz, D. T.",
    title: "Retirement Savings: Choosing a Withdrawal Rate That Is Sustainable",
    publisher: "AAII Journal, 20(2), 16–21",
    year: 1998,
    url: "https://www.aaii.com/journal/article/retirement-savings-choosing-a-withdrawal-rate-that-is-sustainable",
    kind: "academic",
    sections: ["investing"],
    note: 'The "Trinity study."',
  },
  {
    id: "finke-pfau-blanchett-2013",
    authors: "Finke, M., Pfau, W. D. & Blanchett, D. M.",
    title: "The 4 Percent Rule Is Not Safe in a Low-Yield World",
    publisher: "Journal of Financial Planning, 26(6), 46–55",
    year: 2013,
    url: "https://www.financialplanningassociation.org/article/journal/JUN13-4-percent-rule-not-safe-low-yield-world",
    kind: "academic",
    sections: ["investing"],
  },
  {
    id: "guyton-klinger-2006",
    authors: "Guyton, J. T. & Klinger, W. J.",
    title: "Decision Rules and Maximum Initial Withdrawal Rates",
    publisher: "Journal of Financial Planning, 19(3), 48–58",
    year: 2006,
    url: "https://www.financialplanningassociation.org/article/journal/MAR06-decision-rules-and-maximum-initial-withdrawal-rates",
    kind: "practitioner",
    sections: ["investing"],
  },
  {
    id: "morningstar-retirement-income",
    authors: "Morningstar (Benz, C., Ptak, J. & Rekenthaler, J.)",
    title: "The State of Retirement Income",
    publisher: "Morningstar",
    year: "updated regularly",
    url: "https://www.morningstar.com/lp/the-state-of-retirement-income",
    kind: "industry",
    sections: ["investing"],
    note: 'Annual estimate of a "safe" starting withdrawal rate given current bond yields and valuations.',
  },
  {
    id: "ssa-retirement",
    authors: "Social Security Administration",
    title: "Retirement benefits",
    year: "updated regularly",
    url: "https://www.ssa.gov/benefits/retirement/",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "ssa-my-account",
    authors: "Social Security Administration",
    title: "my Social Security account",
    year: "updated regularly",
    url: "https://www.ssa.gov/myaccount/",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "ssa-full-retirement-age",
    authors: "Social Security Administration",
    title: "Retirement age and benefit reduction",
    year: "updated regularly",
    url: "https://www.ssa.gov/benefits/retirement/planner/agereduction.html",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "ssa-fairness-act",
    authors: "Social Security Administration",
    title: "Social Security Fairness Act: Windfall Elimination Provision (WEP) and Government Pension Offset (GPO)",
    year: 2025,
    url: "https://www.ssa.gov/benefits/retirement/social-security-fairness-act.html",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "fed-inflation-target",
    authors: "Board of Governors of the Federal Reserve System",
    title: "Why does the Federal Reserve aim for inflation of 2 percent over the longer run?",
    year: "updated regularly",
    url: "https://www.federalreserve.gov/faqs/economy_14400.htm",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "fed-g19",
    authors: "Board of Governors of the Federal Reserve System",
    title: "Consumer Credit – G.19 (interest rates on credit card plans)",
    year: "updated regularly",
    url: "https://www.federalreserve.gov/releases/g19/current/default.htm",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "irs-pub-969",
    authors: "Internal Revenue Service",
    title: "Publication 969: Health Savings Accounts and Other Tax-Favored Health Plans",
    year: "updated regularly",
    url: "https://www.irs.gov/publications/p969",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "irs-pub-590a",
    authors: "Internal Revenue Service",
    title: "Publication 590-A: Contributions to Individual Retirement Arrangements (IRAs)",
    year: "updated regularly",
    url: "https://www.irs.gov/publications/p590a",
    kind: "government",
    sections: ["investing"],
    note: "Includes the rule (from the SECURE Act of 2019) that taxable non-tuition fellowship and stipend payments count as compensation for IRA contributions.",
  },
  {
    id: "irs-457b",
    authors: "Internal Revenue Service",
    title: "IRC 457(b) deferred compensation plans",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/irc-457b-deferred-compensation-plans",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "irs-403b",
    authors: "Internal Revenue Service",
    title: "IRC 403(b) tax-sheltered annuity plans",
    year: "updated regularly",
    url: "https://www.irs.gov/retirement-plans/irc-403b-tax-sheltered-annuity-plans",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "investor-gov-red-flags",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Red flags of fraud",
    publisher: "Investor.gov",
    year: "updated regularly",
    url: "https://www.investor.gov/protect-your-investments/fraud/how-avoid-fraud/red-flags-fraud",
    kind: "regulator",
    sections: ["investing"],
  },
  {
    id: "investor-gov-ponzi",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Ponzi scheme",
    publisher: "Investor.gov",
    year: "updated regularly",
    url: "https://www.investor.gov/protect-your-investments/fraud/types-fraud/ponzi-scheme",
    kind: "regulator",
    sections: ["investing"],
  },
  {
    id: "investor-gov-crypto",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Crypto assets",
    publisher: "Investor.gov",
    year: "updated regularly",
    url: "https://www.investor.gov/additional-resources/spotlight/crypto-assets",
    kind: "regulator",
    sections: ["investing"],
  },
  {
    id: "finra-day-trading",
    authors: "Financial Industry Regulatory Authority",
    title: "Day trading",
    publisher: "FINRA Investor Insights",
    year: "updated regularly",
    url: "https://www.finra.org/investors/investing/investment-products/stocks/day-trading",
    kind: "regulator",
    sections: ["investing"],
  },
  {
    id: "finra-brokercheck",
    authors: "Financial Industry Regulatory Authority",
    title: "BrokerCheck",
    year: "updated regularly",
    url: "https://brokercheck.finra.org/",
    kind: "regulator",
    sections: ["investing"],
  },
  {
    id: "fdic-deposit-insurance",
    authors: "Federal Deposit Insurance Corporation",
    title: "Deposit insurance",
    year: "updated regularly",
    url: "https://www.fdic.gov/resources/deposit-insurance",
    kind: "government",
    sections: ["investing"],
    note: "Bank deposits are insured up to $250,000 per depositor, per insured bank, for each account ownership category.",
  },
  {
    id: "sec-interest-rate-risk",
    authors: "U.S. Securities and Exchange Commission, Office of Investor Education and Advocacy",
    title: "Investor Bulletin: Interest Rate Risk — When Interest Rates Go Up, Prices of Fixed-Rate Bonds Fall",
    year: 2013,
    url: "https://www.sec.gov/files/ib_interestraterisk.pdf",
    kind: "regulator",
    sections: ["investing"],
  },
  {
    id: "treasurydirect-tips",
    authors: "U.S. Department of the Treasury",
    title: "Treasury Inflation-Protected Securities (TIPS) and I bonds",
    publisher: "TreasuryDirect",
    year: "updated regularly",
    url: "https://www.treasurydirect.gov/marketable-securities/tips/",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "irs-topic-558",
    authors: "Internal Revenue Service",
    title: "Topic no. 558, Additional tax on early distributions from retirement plans other than IRAs",
    year: "updated regularly",
    url: "https://www.irs.gov/taxtopics/tc558",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "irs-topic-409",
    authors: "Internal Revenue Service",
    title: "Topic no. 409, Capital gains and losses",
    year: "updated regularly",
    url: "https://www.irs.gov/taxtopics/tc409",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "irs-pub-590b",
    authors: "Internal Revenue Service",
    title: "Publication 590-B: Distributions from Individual Retirement Arrangements (IRAs)",
    year: "updated regularly",
    url: "https://www.irs.gov/publications/p590b",
    kind: "government",
    sections: ["investing"],
    note: "Includes the ordering rules under which Roth IRA contributions come out before earnings.",
  },
  {
    id: "dalbar-qaib",
    authors: "DALBAR, Inc.",
    title: "Quantitative Analysis of Investor Behavior (QAIB)",
    year: "updated regularly",
    url: "https://www.dalbar.com/",
    kind: "industry",
    sections: ["investing"],
    note: "Annual study of the gap between investor and fund returns; uses a different method from Morningstar's and typically reports larger gaps.",
  },
  {
    id: "spdji-sp500",
    authors: "S&P Dow Jones Indices",
    title: "S&P 500 index",
    year: "updated regularly",
    url: "https://www.spglobal.com/spdji/en/indices/equity/sp-500/",
    kind: "industry",
    sections: ["investing"],
  },
  {
    id: "ssa-trustees",
    authors: "Social Security Administration, Board of Trustees",
    title:
      "The Annual Report of the Board of Trustees of the Federal Old-Age and Survivors Insurance and Federal Disability Insurance Trust Funds",
    year: "updated regularly",
    url: "https://www.ssa.gov/oact/TR/",
    kind: "government",
    sections: ["investing"],
  },
  {
    id: "sec-variable-annuities",
    authors: "U.S. Securities and Exchange Commission",
    title: "Variable Annuities: What You Should Know",
    year: "updated regularly",
    url: "https://www.sec.gov/investor/pubs/varannty.htm",
    kind: "regulator",
    sections: ["investing"],
  },
  {
    id: "sec-iapd",
    authors: "U.S. Securities and Exchange Commission",
    title: "Investment Adviser Public Disclosure",
    year: "updated regularly",
    url: "https://adviserinfo.sec.gov/",
    kind: "regulator",
    sections: ["investing"],
  },
  {
    id: "sec-bitcoin-etp-2024",
    authors: "Gensler, G. (U.S. Securities and Exchange Commission)",
    title: "Statement on the Approval of Spot Bitcoin Exchange-Traded Products",
    year: 2024,
    url: "https://www.sec.gov/newsroom/speeches-statements/gensler-statement-spot-bitcoin-011023",
    kind: "regulator",
    sections: ["investing"],
  },

  // ---------------- Budgeting ----------------
  {
    id: "warren-tyagi-2005",
    authors: "Warren, E. & Tyagi, A. W.",
    title: "All Your Worth: The Ultimate Lifetime Money Plan",
    publisher: "Free Press",
    year: 2005,
    url: "https://www.simonandschuster.com/books/All-Your-Worth/Elizabeth-Warren/9780743269872",
    kind: "practitioner",
    sections: ["budgeting"],
    note: "Popularized the 50/30/20 split of after-tax income into needs, wants and savings.",
  },
  {
    id: "pyhrr-1970",
    authors: "Pyhrr, P. A.",
    title: "Zero-base budgeting",
    publisher: "Harvard Business Review, 48(6), 111–121",
    year: 1970,
    url: "https://hbr.org/1970/11/zero-base-budgeting",
    kind: "practitioner",
    sections: ["budgeting"],
    note: "Introduced zero-based budgeting as a corporate planning method; personal-finance versions adapted it later.",
  },
  {
    id: "clason-1926",
    authors: "Clason, G. S.",
    title: "The Richest Man in Babylon",
    year: 1926,
    url: "https://www.gutenberg.org/ebooks/search/?query=richest+man+in+babylon",
    kind: "practitioner",
    sections: ["budgeting"],
    note: 'Early popular source of the "pay yourself first" idea (saving a set share of income before spending).',
  },
  {
    id: "thaler-benartzi-2004",
    authors: "Thaler, R. H. & Benartzi, S.",
    title: "Save More Tomorrow: Using Behavioral Economics to Increase Employee Saving",
    publisher: "Journal of Political Economy, 112(S1), S164–S187",
    year: 2004,
    url: "https://doi.org/10.1086/380085",
    kind: "academic",
    sections: ["budgeting"],
    note: "In the first implementation, participants' average saving rate rose from 3.5% to 13.6% over 40 months.",
  },
  {
    id: "madrian-shea-2001",
    authors: "Madrian, B. C. & Shea, D. F.",
    title: "The Power of Suggestion: Inertia in 401(k) Participation and Savings Behavior",
    publisher: "The Quarterly Journal of Economics, 116(4), 1149–1187",
    year: 2001,
    url: "https://doi.org/10.1162/003355301753265543",
    kind: "academic",
    sections: ["budgeting"],
    note: "Automatic enrollment raised 401(k) participation among new employees from 37% to 86%.",
  },
  {
    id: "johnson-goldstein-2003",
    authors: "Johnson, E. J. & Goldstein, D.",
    title: "Do Defaults Save Lives?",
    publisher: "Science, 302(5649), 1338–1339",
    year: 2003,
    url: "https://doi.org/10.1126/science.1091721",
    kind: "academic",
    sections: ["budgeting"],
  },
  {
    id: "fed-shed",
    authors: "Board of Governors of the Federal Reserve System",
    title: "Economic Well-Being of U.S. Households (Survey of Household Economics and Decisionmaking)",
    year: "updated regularly",
    url: "https://www.federalreserve.gov/consumerscommunities/shed.htm",
    kind: "government",
    sections: ["budgeting"],
    note: "Annual survey including how adults would cover an unexpected $400 expense.",
  },
  {
    id: "cfpb-bank-statements",
    authors: "Consumer Financial Protection Bureau",
    title: "Spending tracker (Your Money, Your Goals tool)",
    year: "updated regularly",
    url: "https://files.consumerfinance.gov/f/documents/cfpb_your-money-your-goals_spending-tracker_tool.pdf",
    kind: "regulator",
    sections: ["budgeting"],
  },
];

export const sourcesById: ReadonlyMap<string, Source> = new Map(sources.map((s) => [s.id, s]));

export function getSource(id: string): Source {
  const s = sourcesById.get(id);
  if (!s) throw new Error(`Unknown source id "${id}". Add it to src/content/sources.ts.`);
  return s;
}

/** A short "Author, Year" label for inline citations. */
export function shortCitation(s: Source): string {
  const shortAuthor = institutionShortName(s.authors);
  return typeof s.year === "number" ? `${shortAuthor}, ${s.year}` : shortAuthor;
}

const institutionAbbreviations: Array<[RegExp, string]> = [
  [/Securities and Exchange Commission/, "SEC"],
  [/Consumer Financial Protection Bureau/, "CFPB"],
  [/Federal Trade Commission/, "FTC"],
  [/Internal Revenue Service/, "IRS"],
  [/Bureau of Labor Statistics/, "BLS"],
  [/Housing and Urban Development/, "HUD"],
  [/Financial Industry Regulatory Authority/, "FINRA"],
  [/Federal Reserve/, "Federal Reserve"],
  [/National Foundation for Credit Counseling/, "NFCC"],
];

function institutionShortName(authors: string): string {
  for (const [re, abbr] of institutionAbbreviations) {
    if (re.test(authors)) return abbr;
  }
  // People: "Sharpe, W. F." -> "Sharpe"; "Barber, B. M. & Odean, T." -> "Barber & Odean".
  const people = authors
    .split(/\s*(?:&|\band\b)\s*/)
    .flatMap((part) => part.split(/,\s*(?=[A-Z][a-z])/))
    .map((a) => a.split(",")[0].trim());
  if (people.length > 2) return `${people[0]} et al.`;
  return people.join(" & ");
}

/** Full reference in a consistent, readable format. */
export function fullCitation(s: Source): string {
  const year = typeof s.year === "number" ? ` (${s.year}).` : ".";
  const publisher = s.publisher ? ` ${s.publisher}.` : "";
  return `${s.authors}${year} ${s.title}${endPunct(s.title)}${publisher}`;
}

/** A period after a title, unless it already ends in punctuation. */
export function endPunct(title: string): string {
  return /[.?!]$/.test(title) ? "" : ".";
}
